"""empty message

Revision ID: 0c17ab3aebb2
Revises: 751123b23412
Create Date: 2024-03-21 07:12:10.574210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c17ab3aebb2'
down_revision = '751123b23412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('UP', 'DOWN', name='voteenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['discussion_answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'answer_id', name='user_answer_uc')
    )
    with op.batch_alter_table('discussion_answer', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.INTEGER(), nullable=False))

    op.drop_table('answer_vote')
    # ### end Alembic commands ###
