"""empty message

Revision ID: 3a84eb47b87a
Revises: 0c17ab3aebb2
Create Date: 2024-03-24 19:59:06.301903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a84eb47b87a'
down_revision = '0c17ab3aebb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chargily_product_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('api_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chargily_price_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_plan', schema=None) as batch_op:
        batch_op.drop_column('chargily_price_id')

    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.drop_column('chargily_product_id')

    # ### end Alembic commands ###
