"""empty message

Revision ID: 3bee94ceda90
Revises: f044edda1272
Create Date: 2024-04-24 14:13:08.035624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bee94ceda90'
down_revision = 'f044edda1272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
