"""empty message

Revision ID: 43964e3d8217
Revises: 
Create Date: 2024-03-14 16:32:33.070767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43964e3d8217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion')
    # ### end Alembic commands ###
