"""empty message

Revision ID: 5cd013ddb01d
Revises: 
Create Date: 2024-04-17 15:26:32.750706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd013ddb01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('request_method', sa.String(), nullable=False),
    sa.Column('request_body', sa.String(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=False),
    sa.Column('request_at', sa.DateTime(), nullable=False),
    sa.Column('response_at', sa.DateTime(), nullable=False),
    sa.Column('response_time', sa.Interval(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_key'], ['api_key.key'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['api_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_request')
    # ### end Alembic commands ###
