"""empty message

Revision ID: 751123b23412
Revises: 
Create Date: 2024-03-18 21:00:41.890683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751123b23412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_version_endpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('request_body', sa.String(length=2048), nullable=False),
    sa.Column('response_body', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['version'], ['api_version.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_version_endpoint')
    # ### end Alembic commands ###
