"""empty message

Revision ID: 7735ce7d40e4
Revises: e64e1147e196
Create Date: 2024-03-02 20:26:29.664873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735ce7d40e4'
down_revision = 'e64e1147e196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_version_endpoint',
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('request_body', sa.String(length=2048), nullable=False),
    sa.Column('response_body', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['version'], ['api_version.version'], ),
    sa.PrimaryKeyConstraint('api_id', 'version', 'endpoint', 'method')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_version_endpoint')
    # ### end Alembic commands ###
