"""adding api models

Revision ID: cda1af43fae5
Revises: 761d24281b2c
Create Date: 2024-03-01 23:31:19.691048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda1af43fae5'
down_revision = '761d24281b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_version_header',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_version_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_version_plan',
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('max_requests', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.PrimaryKeyConstraint('api_id', 'api_version', 'name')
    )
    op.create_table('api_version_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('request_at', sa.DateTime(), nullable=True),
    sa.Column('request_end_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('request_params', sa.String(length=255), nullable=False),
    sa.Column('request_query', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_version_key.id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_version_request')
    op.drop_table('api_version_plan')
    op.drop_table('api_version_key')
    op.drop_table('api_version_header')
    # ### end Alembic commands ###
