"""empty message

Revision ID: e03f30f38923
Revises: 3bee94ceda90
Create Date: 2024-04-24 14:14:39.665720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03f30f38923'
down_revision = '3bee94ceda90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
