"""empty message

Revision ID: e64e1147e196
Revises: 58826e8222ed
Create Date: 2024-03-02 20:22:11.140312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64e1147e196'
down_revision = '58826e8222ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_version_request')
    op.drop_table('api_version_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_version_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_id', sa.INTEGER(), nullable=True),
    sa.Column('api_version', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('max_requests', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_version_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_id', sa.INTEGER(), nullable=True),
    sa.Column('api_version', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('api_key_id', sa.INTEGER(), nullable=True),
    sa.Column('request_at', sa.DATETIME(), nullable=True),
    sa.Column('request_end_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('request_params', sa.VARCHAR(length=255), nullable=False),
    sa.Column('request_query', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_version.api_id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_version_key.id'], ),
    sa.ForeignKeyConstraint(['api_version'], ['api_version.version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
