"""empty message

Revision ID: f044edda1272
Revises: 5cd013ddb01d
Create Date: 2024-04-24 14:03:05.933714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f044edda1272'
down_revision = '5cd013ddb01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
